In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Setup complete")

Setup complete

In [2]:
import nflreadpy as nfl

seasons = list(range(2016, 2026))

player_stats = nfl.load_player_stats(seasons)
rosters = nfl.load_rosters(seasons)
schedules = nfl.load_schedules(seasons)

print(player_stats.shape)
print(rosters.shape)
print(schedules.shape)

(182252, 115)
(31005, 36)
(2761, 46)

In [4]:
player_stats.head()

shape: (5, 115)
┌────────────┬────────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ player_id  ┆ player_nam ┆ player_di ┆ position ┆ … ┆ gwfg_dist ┆ fantasy_p ┆ fantasy_p ┆ game_id │
│ ---        ┆ e          ┆ splay_nam ┆ ---      ┆   ┆ ance      ┆ oints     ┆ oints_ppr ┆ ---     │
│ str        ┆ ---        ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str     │
│            ┆ str        ┆ ---       ┆          ┆   ┆ i32       ┆ f64       ┆ f64       ┆         │
│            ┆            ┆ str       ┆          ┆   ┆           ┆           ┆           ┆         │
╞════════════╪════════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ 00-0004091 ┆ P.Dawson   ┆ Phil      ┆ K        ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ null    │
│            ┆            ┆ Dawson    ┆          ┆   ┆           ┆           ┆           ┆         │
│ 00-0016919 ┆ A.Vinatier ┆ Adam      ┆ K        ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ null    │
│            ┆ i          ┆ Vinatieri ┆          ┆   ┆           ┆           ┆           ┆         │
│ 00-0019646 ┆ S.Janikows ┆ Sebastian ┆ K        ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ null    │
│            ┆ ki         ┆ Janikowsk ┆          ┆   ┆           ┆           ┆           ┆         │
│            ┆            ┆ i         ┆          ┆   ┆           ┆           ┆           ┆         │
│ 00-0019714 ┆ S.Lechler  ┆ Shane     ┆ P        ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ null    │
│            ┆            ┆ Lechler   ┆          ┆   ┆           ┆           ┆           ┆         │
│ 00-0020337 ┆ S.Smith    ┆ Steve     ┆ WR       ┆ … ┆ 0         ┆ 1.9       ┆ 6.9       ┆ null    │
│            ┆            ┆ Smith     ┆          ┆   ┆           ┆           ┆           ┆         │
└────────────┴────────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴─────────┘

In [6]:
player_stats.columns

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'season',
 'week',
 'season_type',
 'team',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'passing_interceptions',
 'sacks_suffered',
 'sack_yards_lost',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_cpoe',
 'passing_2pt_conversions',
 'pacr',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'def_tackles_solo',
 'def_tackles_with_assist',
 'def_tackle_assists',
 'def_tackles_for_loss',
 'def_tackles_for_loss_yards',
 'def_fumbles_forced',
 'def_sacks',
 'def_sack_yards',
 'def_qb_hits',
 'def_interceptions',
 'def_interception_yards',
 'def_pass_defended',
 'def_tds',
 'def_fumbles',
 'def_safeties',
 'misc_yards',
 'fumble_recovery_own',
 'fumble_recovery_yards_own',
 'fumble_recovery_opp',
 'fumble_recovery_yards_opp',
 'fumble_recovery_tds',
 'penalties',
 'penalty_yards',
 'punt_returns',
 'punt_return_yards',
 'kickoff_returns',
 'kickoff_return_yards',
 'fg_made',
 'fg_att',
 'fg_missed',
 'fg_blocked',
 'fg_long',
 'fg_pct',
 'fg_made_0_19',
 'fg_made_20_29',
 'fg_made_30_39',
 'fg_made_40_49',
 'fg_made_50_59',
 'fg_made_60_',
 'fg_missed_0_19',
 'fg_missed_20_29',
 'fg_missed_30_39',
 'fg_missed_40_49',
 'fg_missed_50_59',
 'fg_missed_60_',
 'fg_made_list',
 'fg_missed_list',
 'fg_blocked_list',
 'fg_made_distance',
 'fg_missed_distance',
 'fg_blocked_distance',
 'pat_made',
 'pat_att',
 'pat_missed',
 'pat_blocked',
 'pat_pct',
 'gwfg_made',
 'gwfg_att',
 'gwfg_missed',
 'gwfg_blocked',
 'gwfg_distance',
 'fantasy_points',
 'fantasy_points_ppr',
 'game_id']

In [7]:
rosters.head()

shape: (5, 36)
┌────────┬──────┬──────────┬─────────────┬───┬────────────┬─────────────┬────────────┬─────────────┐
│ season ┆ team ┆ position ┆ depth_chart ┆ … ┆ entry_year ┆ rookie_year ┆ draft_club ┆ draft_numbe │
│ ---    ┆ ---  ┆ ---      ┆ _position   ┆   ┆ ---        ┆ ---         ┆ ---        ┆ r           │
│ i32    ┆ str  ┆ str      ┆ ---         ┆   ┆ i32        ┆ i32         ┆ str        ┆ ---         │
│        ┆      ┆          ┆ str         ┆   ┆            ┆             ┆            ┆ i32         │
╞════════╪══════╪══════════╪═════════════╪═══╪════════════╪═════════════╪════════════╪═════════════╡
│ 2016   ┆ SF   ┆ K        ┆ K           ┆ … ┆ 1998       ┆ 1998        ┆ null       ┆ null        │
│ 2016   ┆ IND  ┆ K        ┆ K           ┆ … ┆ 1996       ┆ 1996        ┆ null       ┆ null        │
│ 2016   ┆ ARI  ┆ LS       ┆ LS          ┆ … ┆ 2000       ┆ 2000        ┆ null       ┆ null        │
│ 2016   ┆ ATL  ┆ K        ┆ K           ┆ … ┆ null       ┆ null        ┆ null       ┆ null        │
│ 2016   ┆ NE   ┆ QB       ┆ QB          ┆ … ┆ 2000       ┆ 2000        ┆ NE         ┆ null        │
└────────┴──────┴──────────┴─────────────┴───┴────────────┴─────────────┴────────────┴─────────────┘

In [8]:
rosters.columns

['season',
 'team',
 'position',
 'depth_chart_position',
 'jersey_number',
 'status',
 'full_name',
 'first_name',
 'last_name',
 'birth_date',
 'height',
 'weight',
 'college',
 'gsis_id',
 'espn_id',
 'sportradar_id',
 'yahoo_id',
 'rotowire_id',
 'pff_id',
 'pfr_id',
 'fantasy_data_id',
 'sleeper_id',
 'years_exp',
 'headshot_url',
 'ngs_position',
 'week',
 'game_type',
 'status_description_abbr',
 'football_name',
 'esb_id',
 'gsis_it_id',
 'smart_id',
 'entry_year',
 'rookie_year',
 'draft_club',
 'draft_number']

In [10]:
player_stats.write_csv("../data/raw/player_stats_2016_2025.csv")
rosters.write_csv("../data/raw/rosters_2016_2025.csv")
schedules.write_csv("../data/raw/schedules_2016_2025.csv")